### PR TITLE
Deactivate purging of Tailwind base classes

### PR DESCRIPTION
**Pull request by dominikmayer**
I had issues (#30) where base classes were purged so I let PurgeCSS ignore the site styling as well as the Tailwind basics.

(First time trying pull requests. Please review and let me know if it works or if there is a simpler solution.)

### CODE REVIEW

**Review by dirkolbrich — COMMENTED** [review]
This would ignore all Tailwindcss base styles from purging and make the complete purging process useless.

**Comment by dominikmayer** [comment]
Not sure I understand. Utilities (which I still purge) is the large file with 170.000+ lines or 2,9 MB. Base (540 lines, 3 KB) and components (215 lines, 2 KB) are small in comparison.

I've done two Hugo sites, one with this template and one without and unless I escaped base and components I always ran into issues where necessary classes were purged away. No idea why.

**Comment by dominikmayer** [comment]
But I'm fine with not merging it in here. Just thought others might run into similar issues.

**Comment by dirkolbrich** [comment]
What are your issues? Please describe. Please share your setup as well, so I am able to investigate.

**Comment by dominikmayer** [comment]
I shared the config in the issue (#30).

**Pull request closed without merging**
